# Rename this file to languages.toml to enable multilingual support
[en]
contentDir = "content/en"
languageName = "English"
weight = 2
[en.params]
description = "Minimal in form, vibrant in heart"

[zh]
contentDir = "content"
languageName = "简体中文"
weight = 1
hasCJKLanguage = true
title = "Hugo 主题 Prism"
[zh.params]
description = "极简于形，斑斓于心"