baseurl = "https://prism.cai.im"
title = "Hugo Theme Prism"
copyright = "CC BY-NC-SA 4.0"

[build]
noJSConfigInAssets = false

[author]
name = "Example User"
email = "example@example.com"

[taxonomies]
category = "categories"
tag = "tags"

[outputs]
_merge = "deep"

[markup]
_merge = 'deep'

[caches]
[caches.images]
dir = ':cacheDir/images'

[services]
[services.disqus]
shortname = 'hugo-theme-prism'