siteNamePostfix = "/"
mainSections = ["post"]
rssFullContent = true
Logo = "https://avatars.githubusercontent.com/u/5889006?s=100"
description = "Minimal in form, vibrant in heart"

[Default]
[Default.Hero]
Blurry = true
Vibrant = true

[footer]
since = 2026

[opengraph.twitter]
site = "YOUR_TWITTER_USERNAME"
card = "summary_large_image"